server:
  persistentVolume:
    enabled: true
    size: 20Gi
    storageClass: gp2
    accessModes:
      - ReadWriteOnce

  retention: "15d"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

  service:
    type: LoadBalancer
    servicePort: 80

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true
